name: TableSorter
author: jplarson
category: Interface
tags: [sorting, table sorter, table]
docs: http://github.com/jplarson/TableSorter/blob/master/README.md
demo: http://www.jpl-consulting.com/projects/MooTools/TableSorter/Demo/